[project]
name = "my-cwl-project"
version = "1.0.0"

[tools.crop]
context = "command-line-tools/crop"
path = "cwl-workflow/app-water-bodies-cloud-native.cwl#crop"

[[tools.crop.tests]]
name = "crop-test-greeb"
description = "Test case 1 for crop tool - green band."

[tools.crop.tests.params]
item = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_10TFK_20210713_0_L2A"
aoi = "-121.399,39.834,-120.74,40.472"
epsg = "EPSG:4326"
band = "green"

[tools.crop.tests.execution]
volume = "/calrissian/crop-green"
max_ram = "1G"
max_cores = 1
pod_serviceaccount = "calrissian-sa"

[tools.crop.tests.execution.paths]
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"
usage_report = "usage.json"
tool_logs_basepath = "logs"

[[tools.crop.tests]]
name = "crop-test-nir"
description = "Test case 2 for crop tool - nir band."

[tools.crop.tests.params]
item = "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_10TFK_20210713_0_L2A"
aoi = "-121.399,39.834,-120.74,40.472"
epsg = "EPSG:4326"
band = "nir"

[tools.crop.tests.execution]
volume = "/calrissian/crop-nir"
max_ram = "1G"
max_cores = 1
pod_serviceaccount = "calrissian-sa"

[tools.crop.tests.execution.paths]
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"
usage_report = "usage.json"
tool_logs_basepath = "logs"


[tools.norm_diff]
context = "command-line-tools/norm_diff"
path = "cwl-workflow/app-water-bodies-cloud-native.cwl#norm_diff"

[[tools.norm_diff.tests]]
name = "norm_diff-test"
description = "Test case for norm_diff tool."

[tools.norm_diff.tests.params]
rasters = [{"class"="File", "path"="/calrissian/crop-green/results/crop_green.tif"}, {"class"="File", "path"="/calrissian/crop-nir/results/crop_nir.tif"}]

[tools.norm_diff.tests.execution]
volume = "/calrissian/norm-diff"
max_ram = "1G"
max_cores = 1
pod_serviceaccount = "calrissian-sa"

[tools.norm_diff.tests.execution.paths]
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"
usage_report = "usage.json"
tool_logs_basepath = "logs"





[tools.otsu]
context = "command-line-tools/otsu"
path = "cwl-workflow/app-water-bodies-cloud-native.cwl#otsu"

[[tools.otsu.tests]]
name = "norm_diff-test"
description = "Test case for otsu tool."

[tools.otsu.tests.params]
raster = {"class"="File", "path"="/calrissian/norm-diff/results/norm_diff.tif"}

[tools.otsu.tests.execution]
volume = "/calrissian/otsu"
max_ram = "1G"
max_cores = 1
pod_serviceaccount = "calrissian-sa"

[tools.otsu.tests.execution.paths]
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"
usage_report = "usage.json"
tool_logs_basepath = "logs"


[tools.stac]
context = "command-line-tools/stac"
path = "cwl-workflow/app-water-bodies-cloud-native.cwl#stac"


[build.cluster]
namespace = "eoap-advanced-tooling"
serviceAccount = "kaniko-sa"

[build.container]
registry = "cr.terradue.com/earthquake-monitoring"
secret = "kaniko-secret"

[[workflows]]
path = "cwl-workflow/app-water-bodies-cloud-native.cwl#water-bodies"


[[workflows.tests]]
name = "water-detection-test-1"
description = "Test case 1 for water bodies detection."

[workflows.tests.params]
stac_items = [
    "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_10TFK_20210713_0_L2A",
    "https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_10TFK_20220524_0_L2A"
]
aoi = "-121.399,39.834,-120.74,40.472"
epsg = "EPSG:4326"

[workflows.tests.execution]
volume = "/calrissian"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"

[workflows.tests.execution.paths]
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"
usage_report = "usage.json"
tool_logs_basepath = "logs"


[[workflows]]
path = "cwl-workflow/app-water-body-cloud-native.cwl#water-bodies"
