version: '3'

includes:
  remote: https://raw.githubusercontent.com/eoap/task-files/refs/tags/0.1.0/build-test/Taskfile.yaml

tasks:
  build:
  - task: remote:build

  build-debug:
    cmds: 
    - defer: rm -f skaffold-auto.yaml
    - task: remote:prepare-kaniko
    - |
      skaffold build -f skaffold-auto.yaml 

  build-ttl:
  - task: remote:build-ttl

  prepare:
  - task: remote:prepare-kaniko

  test:
  - task: remote:test

  test-all:
    cmds: 
    - task: test-crop
    - task: test-norm-diff
    - task: test-otsu
    - task: test-stac

  test-crop:
    cmds:
    - task: remote:test-tool
      vars:
        VAR: "crop"

  test-norm-diff:
    cmds:
    - task: remote:test-tool
      vars:
        VAR: "norm_diff"

  test-otsu:
    cmds:
    - task: remote:test-tool
      vars:
        VAR: "otsu" 

  test-stac:
    cmds:
    - task: remote:test-tool
      vars:
        VAR: "stac"
  
  scenario-1:
  - task: remote:test-by-index
    vars:
      VAR: 0