version: '3'

includes:
  remote: https://raw.githubusercontent.com/fabricebrito/eoap-taskfile/refs/heads/main/task-files/Taskfile.yaml

tasks:
  build:
  - task: remote:prepare
  - task: remote:build
  - task: remote:update

  prepare:
  - task: remote:prepare

  test:
  - task: remote:test